name = "rin"
main = "_worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat_v2"]
minify = true
workers_dev = true
routes = [
  { pattern = "rin.rimurux.dpdns.org", custom_domain = true },
  { pattern = "ava.game.naver.com.rin.rimurux.dpdns.org", custom_domain = true },
  { pattern = "df.game.naver.com.rin.rimurux.dpdns.org", custom_domain = true },
  { pattern = "graph.instagram.com.rin.rimurux.dpdns.org", custom_domain = true },
  { pattern = "zaintest.vuclip.com.rin.rimurux.dpdns.org", custom_domain = true },
  { pattern = "support.zoom.us.rin.rimurux.dpdns.org", custom_domain = true },  
  { pattern = "store.linefriends.com.rin.rimurux.dpdns.org", custom_domain = true }, 
  { pattern = "collection.linefriends.com.rin.rimurux.dpdns.org", custom_domain = true },  
  { pattern = "cache.netflix.com.rin.rimurux.dpdns.org", custom_domain = true },
  { pattern = "plus-store.naver.com.rin.rimurux.dpdns.org", custom_domain = true },
]
[unsafe.metadata.observability]
enabled = true

[observability.logs]
enabled = true

workers_dev = true
usage_model = "bundled"

# Env untuk testing
[env.dev]
name = "rin-dev"
workers_dev = true

# Env utama (production) ke domain milikmu
[env.prod]
name = "rin-prod"
zone_id = "17a175a851b66e5e7f6c411f5a29c17f"
route = "https://rimurux.dpdns.org/*"

# Opsional, environment lain
[env.one]
name = "rin-one"
workers_dev = true
